spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miao-mall?rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: mysql
  application:
    name: order-service
server:
  port: 7072

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true