
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miao-mall?rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    username: root
    password: mysql
  application:
    name: product-service
server:
  port: 7071

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: info
    org.springframework.web: error
    org.apache.ibatis: debug
    org.dromara.hmily.demo.bonuspoint: debug
    org.dromara.hmily.demo.lottery: debug
    org.dromara.hmily.demo: debug
    io.netty: error