spring:
  application:
    name: transaction
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
server:
  port: 8080
dubbo:
  scan:
    base-packages: com.github.yooryan.api
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181

logging:
  level:
    root: info
    org.springframework.web: debug
    org.apache.ibatis: debug
    org.dromara.hmily.demo.bonuspoint: debug
    org.dromara.hmily.demo.lottery: debug
    org.dromara.hmily.demo: debug
    io.netty: error